"""empty message

Revision ID: 3aadcfc5f036
Revises: d3e493dec4d5
Create Date: 2022-09-24 17:25:54.231395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aadcfc5f036'
down_revision = 'd3e493dec4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_cup', sa.Column('WebtoonTitle', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_cup', 'WebtoonTitle')
    # ### end Alembic commands ###
